---
title:  'Das Universum -- Einige Gedanken'
author: 
- name: Sebastian Semper
  affiliation: Technische Universität Ilmenau
tags: [Philosophie, Welt, Nachgedachtes]
abstract: |
  Ich weiß noch nicht, was hier auftauchen soll, aber es wird bald passieren
...